### ISSUE TITLE
How do I run the program?

### ISSUE THREAD

**Issue by simonlindholm** [inda18plusplus/ggerholm-crypto#1]
I got "UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 15: invalid continuation byte" when running `pypy3 main.py`. Updating that file to be valid utf8 (does it need to be that, or should it just contain raw bytes?), I get further:

```
Client: Server connection established.
Server: Client connected from ('127.0.0.1', 34014)
Server: Keys generated.
Client: Keys generated.
Client: Public key sent.
Server: Client public key received.
Server: Public key sent.
Server: Secret key sent.
Client: Server public key received.
Client: Secret key received.
Ready to serve:
> help
Command not recognized.
> send 12 hello
Server: Received  {'file_id': 12, 'data': 'hello'}
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    run_client(False)
  File "/home/simon/code/inda/crypto/ggerholm-crypto/network/client.py", line 37, in run_client
    client.send_file(File(fid, data))
  File "/home/simon/code/inda/crypto/ggerholm-crypto/network/client.py", line 174, in send_file
    self._latest_top_hash = get_root_hash(hash_structure, file)
  File "/home/simon/code/inda/crypto/ggerholm-crypto/utils/merkle.py", line 25, in get_root_hash
    structure = node_from_json(structure_json)
  File "/home/simon/code/inda/crypto/ggerholm-crypto/utils/merkle.py", line 9, in node_from_json
    d = json.loads(node_json)
  File "/home/simon/code/blah/pypy3-v5.8.0-linux64/lib-python/3/json/__init__.py", line 318, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Server: Request processed.
```

When I tried `python2 main.py` I instead got "ImportError: No module named network.client"

**Comment by Sourc** [comment]
I'm unsure what the issue is, it works fine on the computers (windows only) that I've tested it on. Using python 3.6+.

**Comment by Sourc** [comment]
I changed the encoding of the client_secret.txt file to fix one issue I found while on Ubuntu. I could not reproduce your issue but it's possible it was solved aswell.

**Comment by simonlindholm** [comment]
The second issue was apparently a CPython vs. Pypy incompatibility.
